/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asdm.examen_saul_rodriguez_naranjo.Vista;

import asdm.examen_saul_rodriguez_naranjo.Modelos.Cocina;
import asdm.examen_saul_rodriguez_naranjo.Modelos.Pedido;
import asdm.examen_saul_rodriguez_naranjo.Modelos.observer.Observer;

/**
 *
 * @author SaulRC1
 */
public class PantallaTipo2 extends javax.swing.JFrame implements Observer {

    private static PantallaTipo2 pantallaTipo2 = new PantallaTipo2();
    private Cocina cocina = Cocina.getCocinaInstance();
    /**
     * Creates new form PantallaTipo2
     * Seguimos el patron Singleton
     */
    private PantallaTipo2() {
        cocina.addObserver(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPedidosPreparados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Pedidos Preparados");

        txtPedidosPreparados.setColumns(20);
        txtPedidosPreparados.setRows(5);
        jScrollPane1.setViewportView(txtPedidosPreparados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addPedido(Pedido pedido) {
        String textoActual = this.txtPedidosPreparados.getText();
        
        textoActual += "\nNumero de Pedido: " + pedido.getNumeroDePedido() 
                + "\n----------------------------" + "\nNombre de Usuario: " 
                + pedido.getUsuario().getNombre();
        this.txtPedidosPreparados.setText(textoActual);
        
    }
    @Override
    public void update() {
        
        this.txtPedidosPreparados.setText("");
        
        for (Pedido ped: this.cocina.getPedidos()) {
            if(ped.getEstado() == Pedido.TERMINADO) {
                this.addPedido(ped);
            } 
        }
    }
    
    public static PantallaTipo2 getPantallaTipo2Instance() {
        return PantallaTipo2.pantallaTipo2;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea txtPedidosPreparados;
    // End of variables declaration//GEN-END:variables
}
