/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asdm.saul_rodriguez_naranjo.practica5_patroniterator.views;

/**
 *
 * @author SaulRC1
 */
public class MenuListaVista extends javax.swing.JFrame {

    /**
     * Creates new form MenuListaVista
     */
    public MenuListaVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtElementosDeLaLista = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnAnadirElemento = new javax.swing.JButton();
        btnComprobarSiTieneElementoSiguiente = new javax.swing.JButton();
        btnObtenerElementoSiguiente = new javax.swing.JButton();
        txtElementoSiguiente = new javax.swing.JTextField();
        btnObtenerElementoAnterior = new javax.swing.JButton();
        txtElementoAnterior = new javax.swing.JTextField();
        txtAnadirElemento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtElementosDeLaLista.setEditable(false);
        txtElementosDeLaLista.setColumns(20);
        txtElementosDeLaLista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtElementosDeLaLista.setRows(5);
        jScrollPane1.setViewportView(txtElementosDeLaLista);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Elementos de la Lista");

        btnAnadirElemento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAnadirElemento.setText("Añadir Elemento");

        btnComprobarSiTieneElementoSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnComprobarSiTieneElementoSiguiente.setText("Comprobar Si Tiene Elemento Siguiente");

        btnObtenerElementoSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnObtenerElementoSiguiente.setText("Obtener Elemento Siguiente");

        txtElementoSiguiente.setEditable(false);
        txtElementoSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnObtenerElementoAnterior.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnObtenerElementoAnterior.setText("Obtener Elemento Anterior");

        txtElementoAnterior.setEditable(false);
        txtElementoAnterior.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtAnadirElemento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Añadir Elemento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnComprobarSiTieneElementoSiguiente)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtElementoAnterior, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnObtenerElementoAnterior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtElementoSiguiente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnObtenerElementoSiguiente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnadirElemento)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txtAnadirElemento))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnadirElemento)
                    .addComponent(txtAnadirElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnComprobarSiTieneElementoSiguiente)
                .addGap(27, 27, 27)
                .addComponent(btnObtenerElementoSiguiente)
                .addGap(18, 18, 18)
                .addComponent(txtElementoSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnObtenerElementoAnterior)
                .addGap(18, 18, 18)
                .addComponent(txtElementoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAnadirElemento;
    public javax.swing.JButton btnComprobarSiTieneElementoSiguiente;
    public javax.swing.JButton btnObtenerElementoAnterior;
    public javax.swing.JButton btnObtenerElementoSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txtAnadirElemento;
    public javax.swing.JTextField txtElementoAnterior;
    public javax.swing.JTextField txtElementoSiguiente;
    public javax.swing.JTextArea txtElementosDeLaLista;
    // End of variables declaration//GEN-END:variables
}
